backend:
  enabled: false
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
  image:
    repository: nginx
    tag: latest
  ports:
    - containerPort: 8080
  env: []
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  livenessProbe:
    httpGet:
      path: /api/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
  readinessProbe:
    httpGet:
      path: /api/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
  service:
    type: ClusterIP
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080

frontend:
  enabled: false
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
  image:
    repository: nginx
    tag: latest
  ports:
    - containerPort: 3000
  env: []
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  livenessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 5
  service:
    type: ClusterIP
    ports:
      - protocol: TCP
        port: 80
        targetPort: 3000

ingress:
  enabled: false
  annotations: {}
  hosts: []
  paths: []
#serviceAccount:
#  create: true
#  annotations: {}
#  name: ""
#
#imagePullSecrets: []
#nameOverride: ""
#fullnameOverride: ""
#podAnnotations: {}
#podSecurityContext: {}
#securityContext: {}
#nodeSelector: {}
#tolerations: []
#affinity: {}
