{{- if .Values.frontend.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            {{ - toYaml .Values.frontend.ports | nindent 12 }}
          env:
            {{ - toYaml .Values.frontend.env | nindent 12 }}
          resources:
            {{ - toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            {{ - toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{ - toYaml .Values.frontend.readinessProbe | nindent 12 }}
{{- else }}
{{- end }}
